@Identity.API_HostAddress = http://localhost:5283

### Register candidate
POST {{Identity.API_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Ana",
  "lastName": "Petrovic",
  "email": "ana@example.com",
  "password": "Pass123!",
  "role": "Candidate"
}

### Login
POST {{Identity.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "ana@example.com",
  "password": "Pass123!"
}

### Current user (paste token from login)
GET {{Identity.API_HostAddress}}/api/auth/me
Authorization: Bearer {{token}}
